# Generated by Django 5.1.3 on 2024-11-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_content_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, upload_to='myapp/static/img'),
        ),
    ]
